name: Build
on:
  push:
    branches: ["*"]
    paths-ignore:
      - "**.md"
      - "example/**"
      - "website/**"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23
        id: go

      - name: Set up Git cookies
        run: bash scripts/gogetcookie.sh

      - name: Build
        run: make build

      # - name: Start containers
      #   run: docker-compose up -d --build

      # - name: Test
      #   run: make testacc OPTS=-coverprofile=c.out
      #   env:
      #     AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      #     AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      #     AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}

      # - name: Send code coverage report
      #   uses: aktions/codeclimate-test-reporter@v1
      #   with:
      #     codeclimate-test-reporter-id: ${{ secrets.CC_TEST_REPORTER_ID }}
      #     command: after-build --prefix github.com/zklinger/terraform-provider-auth0

      # - name: Stop containers
      #   if: always()
      #   run: docker-compose down
