name: Release
on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Determine version
        run: echo VERSION=$(echo $GITHUB_REF | cut -d / -f 3 | sed -e "s/^v//") >> $GITHUB_ENV

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
        id: gpg

      - name: Go release
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean --config=.github/release.yml
        env:
          GPG_FINGERPRINT: ${{ steps.gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
